=== Geonovum/LVBB-test-repository/v0.98-beta/Opdracht/xsd_stop_0.97.1_manifest-ow.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified"
  targetNamespace="https://standaarden.overheid.nl/stop/DSO-PI10"
  xmlns:stoplap="https://standaarden.overheid.nl/stop/DSO-PI10"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="Modules">
    <xs:annotation>
      <xs:documentation>Root element van CIM-OW.xml, speficiek bedoeld voor de v0.97 keten in PI10.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="1" ref="stoplap:domein" />
        <xs:element maxOccurs="unbounded" minOccurs="1" ref="stoplap:RegelingVersie" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="domein">
    <xs:annotation>
      <xs:documentation>
        Het domein geeft het wetgevingsdomein aan en is 
        nodig om de verwerking in de keten beter te laten verlopen. 
        Voor PI10 STOPLAP heeft het element een vaste waarde "omgevingswet".
        .</xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:enumeration value="omgevingswet" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="RegelingVersie">
    <xs:annotation>
      <xs:documentation>
				CIM-OW bestanden die horen bij een specifieke versie van een regeling.
				In de PI10 keten leidt een versie van een regeling zoals bevoegd gezag 
				die kent ook tot een toestand. De verwijzing kan in de modulaire versie
				van STOP anders zijn in verband met het ondersteunen van complexere
				consolidatiescenario's.
			</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="1" ref="stoplap:FRBRwork" />
        <xs:element maxOccurs="1" minOccurs="1" ref="stoplap:FRBRExpression" />
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="stoplap:Bestand">
          <xs:annotation>
            <xs:documentation>
						Bestandsnaam van de module volgens CIM-OW opmaak.
						Het bestand moet ook in de manifest voorkomen.
					</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="FRBRwork" type="xs:anyURI">
    <xs:annotation>
      <xs:documentation>
        FRBR uri van de regeling, correspondeert met de
        AKNIdentification / FRBRWork / FRBRthis van de regeling
        zoals bevoegd gezag die vaststelt.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="FRBRExpression" type="xs:anyURI">
    <xs:annotation>
      <xs:documentation>
        FRBR uri van de versie van de regeling, correspondeert met de
        imop:wordtVersie uit het besluit. Deze identificatie is ook beschikbaar
        in de toestand-XML.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
  <xs:element name="Bestand">
    <xs:annotation>
      <xs:documentation>Basistype voor alle leveringen via Digikoppeling ebMS.</xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="1" minOccurs="1" ref="stoplap:naam" />
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="stoplap:objecttype" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="naam">
    <xs:annotation>
      <xs:documentation>
        Naam van het bestand; moet overeenkomen met de naam
        zoals in manifest.xml is opgenomen.
      </xs:documentation>
    </xs:annotation>
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:pattern value="[a-zA-Z0-9\-.]*"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="objecttype" type="xs:string">
    <xs:annotation>
      <xs:documentation>
        Type van de objecten die in het bestand voorkomen.
        De toegestane waarde voor het objecttype is beschreven in de CIM-OW documentatie.
      </xs:documentation>
    </xs:annotation>
  </xs:element>
</xs:schema>

=== Geonovum/LVBB-test-repository/v0.98.1-beta/IMOW/manifest-ow.xml
<?xml version="1.0" encoding="utf-8"?>
<Modules xmlns="https://standaarden.overheid.nl/stop/DSO-PI10" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="https://standaarden.overheid.nl/stop/DSO-PI10 xsd_stop_0.97.1_manifest-ow.xsd">
  <domein>omgevingswet</domein>
  <RegelingVersie>
    <FRBRwork>/akn/nl/act/gm0037/2019/3520</FRBRwork>
    <FRBRExpression>/akn/nl/act/gm0037/2019/3520/nld@2019-01-16</FRBRExpression>
    <Bestand>
      <naam>owActiviteiten-Gemeentestad</naam>
      <objecttype>Activiteit</objecttype>
    </Bestand>
    <Bestand>
      <naam>owGebiedsaanwijzingen-Gemeentestad.xml</naam>
      <objecttype>Gebiedsaanwijzing</objecttype>
    </Bestand>
    <Bestand>
      <naam>owPons-Gemeentestad.xml</naam>
      <objecttype>Pons</objecttype>
    </Bestand>
    <Bestand>
      <naam>owOmgevingsNormOmgevingswaarde.xml</naam>
      <objecttype>OmgevingsNormOmgevingswaarde</objecttype>
    </Bestand>
    <Bestand>
      <naam>owLocaties-Gemeentestad.xml</naam>
      <objecttype>Gebiedengroep</objecttype>
      <objecttype>Gebied</objecttype>
    </Bestand>
    <Bestand>
      <naam>owRegeltekst-Gemeentestad.xml</naam>
      <objecttype>Regeltekst</objecttype>
    </Bestand>
  </RegelingVersie>
</Modules>
